[project]
name = "projeto-streamlit-pratico"
version = "0.1.0"
description = ""
authors = [
    {name = "Douglas França",email = "douglas_nts@hotmail.com"}
]
readme = "README.md"
package-mode = false
requires-python = ">=3.11"
dependencies = [
    "streamlit (>=1.37.1,<2.0.0)",
    "pandas (>=2.2.2,<3.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
